<a href="https://colab.research.google.com/github/pakyeon/deep-rl-class-ko/blob/main/notebooks/ko/unit2/unit2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 유닛 2: FrozenLake-v1 ⛄ 및 Taxi-v3 🚕를 사용한 Q-Learning

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/thumbnail.jpg" alt="Unit 2 Thumbnail">

이 노트북에서는 **처음으로 강화 학습 에이전트를 직접 코딩**하여 FrozenLake ❄️를 Q-Learning을 통해 플레이하고, 이를 커뮤니티와 공유하며 다양한 설정을 실험해볼 수 있습니다.

⬇️ 아래는 **단 몇 분 만에 여러분이 얻게 될 결과물의 예시입니다.** ⬇️

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/envs.gif" alt="Environments"/>

### 🎮 환경:

- [FrozenLake-v1](https://gymnasium.farama.org/environments/toy_text/frozen_lake/)
- [Taxi-v3](https://gymnasium.farama.org/environments/toy_text/taxi/)

### 📚 RL 라이브러리:

- Python 및 NumPy  
- [Gymnasium](https://gymnasium.farama.org/)

우리는 튜토리얼을 지속적으로 개선하고 있으니, **이 노트북에서 문제를 발견하셨다면** [GitHub 저장소에 이슈를 등록해 주세요](https://github.com/huggingface/deep-rl-class/issues).

## 이 노트북의 목표 🏆

이 노트북을 마치면, 여러분은 다음을 할 수 있게 됩니다:

- **Gymnasium** 환경 라이브러리를 사용할 수 있습니다.  
- Q-Learning 에이전트를 처음부터 직접 코딩할 수 있습니다.  
- **학습시킨 에이전트와 코드를 Hub에 업로드**하고, 멋진 비디오 리플레이와 평가 점수 🔥까지 함께 공유할 수 있습니다.

## 이 노트북은 딥 강화 학습 과정(Deep Reinforcement Learning Course)의 일부입니다

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/deep-rl-course-illustration.jpg" alt="Deep RL Course illustration"/>

이 무료 강좌에서는 다음을 배우게 됩니다:

- 📖 **이론과 실습**을 통해 딥 강화 학습(Deep Reinforcement Learning)을 학습합니다.  
- 🧑‍💻 Stable Baselines3, RL Baselines3 Zoo, CleanRL, Sample Factory 2.0 같은 **유명한 딥 RL 라이브러리들을 사용하는 방법**을 배웁니다.  
- 🤖 **다양한 독특한 환경에서 에이전트를 훈련**시킵니다.

그리고 그 외 더 많은 내용을 배울 수 있어요. 📚 전체 커리큘럼은 👉 [여기에서 확인하세요](https://simoninithomas.github.io/deep-rl-course)

또한 **[이곳을 클릭해 코스에 등록하세요](http://eepurl.com/ic5ZUD)**  
(등록 시 이메일을 수집하는 이유는 각 유닛이 공개될 때 링크를 보내드리고, 챌린지나 업데이트 정보를 전달해드리기 위함입니다.)

커뮤니티와 교류하고 저희와 소통하려면 디스코드 서버에 참여하는 것이 가장 좋습니다 👉🏻 https://discord.gg/ydHrjt3WP5

## 사전 준비 사항 🏗️

이 노트북을 시작하기 전에 다음을 완료해야 합니다:

🔲 📚 **[Unit 2의 Q-Learning 이론](https://huggingface.co/deep-rl-course/unit2/introduction)**을 학습하세요 🤗

## Q-Learning에 대한 간략한 요약

*Q-Learning*은 다음과 같은 방식으로 작동하는 **강화 학습(RL) 알고리즘**입니다:

- *Q-함수(Q-Function)*를 학습하며, 이는 **행동 가치 함수(action-value function)**입니다. 이 함수는 내부 메모리로 *Q-테이블(Q-table)*에 **모든 상태-행동 쌍의 값을 저장**합니다.

- 어떤 상태와 행동이 주어졌을 때, Q-함수는 **Q-테이블에서 해당 값**을 찾아냅니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-function-2.jpg" alt="Q function"  width="100%"/>

- 훈련이 완료되면, 우리는 **최적의 Q-함수**, 즉 **최적의 Q-테이블**을 얻게 됩니다.

- 그리고 **최적의 Q-함수**를 갖게 되면, 결국 **각 상태마다 최적의 행동을 알 수 있으므로, 이는 곧 최적의 정책(optimal policy)**을 의미합니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/link-value-policy.jpg" alt="Link value policy"  width="100%"/>

하지만 초반에는 **Q-테이블이 아무 쓸모 없습니다.** 각 상태-행동 쌍에 대해 임의의 값(보통 0으로 초기화됨)을 주기 때문입니다. 그러나 환경을 탐험하고 Q-테이블을 점차 업데이트하면서 **더 나은 근사값**을 얻게 됩니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/q-learning.jpeg" alt="q-learning.jpeg" width="100%"/>

다음은 Q-Learning의 의사 코드(pseudocode)입니다:

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-learning-2.jpg" alt="Q-Learning" width="100%"/>

# 첫 번째 강화 학습 알고리즘을 코딩해 보겠습니다. 🚀

이 실습을 [인증 과정](https://huggingface.co/deep-rl-course/en/unit0/introduction#certification-process)에 포함시키기 위해서는, 학습시킨 Taxi 모델을 Hub에 업로드하고 **결과가 4.5 이상**이어야 합니다.

결과를 확인하려면, [리더보드](https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard)로 이동하여 본인의 모델을 찾으세요.  
**결과 값 = 평균 보상(mean_reward) - 보상의 표준편차(std of reward)** 입니다.

인증 절차에 대한 더 자세한 정보는 아래 링크에서 확인할 수 있습니다 👉  
[https://huggingface.co/deep-rl-course/en/unit0/introduction#certification-process](https://huggingface.co/deep-rl-course/en/unit0/introduction#certification-process)

## 의존성 설치 및 가상 디스플레이 생성 🔽

이 노트북에서는 리플레이 영상을 생성할 필요가 있습니다. Colab에서는 **환경을 렌더링하기 위한 가상 화면(virtual screen)**이 필요하며, 이를 통해 프레임을 녹화할 수 있습니다.

따라서 아래 셀은 필요한 라이브러리들을 설치하고 가상 화면을 생성 및 실행합니다 🖥

설치될 주요 라이브러리는 다음과 같습니다:

- `gymnasium`: FrozenLake-v1 ⛄ 및 Taxi-v3 🚕 환경을 포함합니다.  
- `pygame`: FrozenLake-v1 및 Taxi-v3의 UI 렌더링에 사용됩니다.  
- `numpy`: Q-테이블을 다루는 데 사용됩니다.  

🤗 Hugging Face Hub는 누구나 모델과 데이터셋을 공유하고 탐색할 수 있는 중심 플랫폼입니다. 버전 관리, 지표, 시각화 등의 기능이 포함되어 있어 다른 사람들과 쉽게 협업할 수 있습니다.

Q-Learning을 사용하는 모든 딥 RL 모델은 여기에서 확인할 수 있어요 👉  
[https://huggingface.co/models?other=q-learning](https://huggingface.co/models?other=q-learning)

In [ ]:
!pip install -r https://raw.githubusercontent.com/huggingface/deep-rl-class/main/notebooks/unit2/requirements-unit2.txt

In [ ]:
!sudo apt-get update
!sudo apt-get install -y python3-opengl
!apt install ffmpeg xvfb
!pip3 install pyvirtualdisplay

새로 설치된 라이브러리를 적용하려면 **런타임을 재시작해야 할 때가 있습니다**.  
다음 셀은 **런타임을 강제로 중단시킬 것이므로, 재연결 후 여기부터 코드를 다시 실행해야 합니다**.  
이 트릭 덕분에 **가상 화면을 정상적으로 실행할 수 있을 것입니다**.

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
# Virtual display
from pyvirtualdisplay import Display

virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()

## 패키지 임포트 📦

설치한 라이브러리 외에도, 다음과 같은 추가 패키지를 사용합니다:

- `random`: 무작위 수를 생성하기 위해 사용됩니다 (에이전트의 ε-탐욕 정책에서 활용됩니다).  
- `imageio`: 리플레이 비디오를 생성하는 데 사용됩니다.

In [ ]:
import numpy as np
import gymnasium as gym
import random
import imageio
import os
import tqdm

import pickle5 as pickle
from tqdm.notebook import tqdm

이제 Q-Learning 알고리즘을 코딩할 준비가 되었습니다 🔥

# Part 1: 프로즌 레이크 ⛄ (미끄럽지 않은 버전)

## [FrozenLake 환경 ⛄] 생성 및 이해하기  
---  

💡 환경을 사용하기 시작할 때 좋은 습관은 **문서를 확인하는 것**입니다.  

👉 https://gymnasium.farama.org/environments/toy_text/frozen_lake/  

---  

Q-Learning 에이전트를 훈련시켜 **시작 지점(S)에서 목표 지점(G)까지 얼어있는 타일(F)만 밟고 구멍(H)은 피해서 이동**하도록 만들 것입니다.  

환경 크기는 두 가지 중 선택할 수 있습니다:  

- `map_name="4x4"`: 4x4 격자  
- `map_name="8x8"`: 8x8 격자  

환경은 두 가지 모드를 가집니다:  

- `is_slippery=False`: 얼어있는 호수가 미끄럽지 않아서 에이전트가 **항상 의도한 방향으로 이동**합니다 (결정적).  
- `is_slippery=True`: 얼어있는 호수가 미끄러워서 에이전트가 **항상 의도한 방향으로 이동하지 않을 수 있습니다** (확률적).

지금은 간단하게 4x4 맵과 미끄럽지 않은 설정으로 진행합니다.  
환경을 시각화하는 방식을 지정하는 `render_mode`라는 매개변수를 추가합니다.  
이번 경우에는 **환경의 영상을 마지막에 기록하고 싶기 때문에 render_mode를 `rgb_array`로 설정해야 합니다**.

[문서에 설명된 것처럼](https://gymnasium.farama.org/api/env/#gymnasium.Env.render), `"rgb_array"`는 환경의 현재 상태를 나타내는 **단일 프레임을 반환**합니다.  
이 프레임은 `(x, y, 3)` 형태의 `np.ndarray`로, `x`×`y` 픽셀 이미지의 RGB 값을 나타냅니다.

In [ ]:
# 4x4 맵과 ​​미끄럽지 않은 버전, render_mode="rgb_array"를 사용하여 FrozenLake-v1 환경을 만듭니다.
env = gym.make() # TODO 올바른 매개변수를 사용하세요

### 해결 방법

In [ ]:
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False, render_mode="rgb_array")

다음과 같이 사용자 지정 격자를 직접 만들 수도 있습니다:

```python
desc = ["SFFF", "FHFH", "FFFH", "HFFG"]
gym.make('FrozenLake-v1', desc=desc, is_slippery=True)
```

하지만 지금은 **기본 환경**을 사용할 것입니다.

### 환경이 어떻게 생겼는지 살펴보자:

In [ ]:
# 우리는 gym.make("<name_of_the_environment>")를 사용하여 환경을 생성합니다. - `is_slippery=False`: 미끄럽지 않은 얼어붙은 호수 환경에서는 에이전트가 항상 의도한 방향으로 이동합니다 (결정론적).
print("_____관찰 공간_____ \n")
print("관찰 공간:", env.observation_space)
print("샘플 관찰값:", env.observation_space.sample())  # 임의의 관찰값 출력

`Observation Space Shape Discrete(16)`을 통해 관찰값이 정수이며, 이는 **에이전트의 현재 위치를 current_row * ncols + current_col (row와 col은 0부터 시작)** 으로 표현한다는 것을 알 수 있습니다.

예를 들어, 4x4 맵에서 목표 위치는 다음과 같이 계산할 수 있습니다: 3 * 4 + 3 = 15. 가능한 관찰값의 수는 맵의 크기에 따라 달라집니다. **예를 들어, 4x4 맵에는 16개의 가능한 관찰값이 있습니다.**

예시로, 상태(state) = 0은 다음과 같은 모습입니다:

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/frozenlake.png" alt="FrozenLake">

In [ ]:
print("\n _____행동 공간_____ \n")
print("행동 공간 크기:", env.action_space.n)
print("샘플 행동:", env.action_space.sample())  # 임의의 행동 선택

행동 공간(에이전트가 취할 수 있는 가능한 행동들의 집합)은 4개의 이산적인 행동으로 구성되어 있습니다 🎮:  
- 0: 왼쪽으로 이동  
- 1: 아래로 이동  
- 2: 오른쪽으로 이동  
- 3: 위로 이동  

보상 함수 💰:  
- 목표 지점 도달: +1  
- 구멍에 빠짐: 0  
- 얼어있는 칸 도달: 0

## Q-테이블 생성 및 초기화 🗄️

(👀 의사코드의 Step 1)

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-learning-2.jpg" alt="Q-Learning" width="100%"/>

이제 Q-테이블을 초기화할 시간입니다!  
몇 개의 행(상태)과 열(행동)을 사용할지 알기 위해, 우리는 행동 공간과 관찰 공간을 알아야 합니다.  
이 값들은 앞에서 알았지만, 알고리즘이 다양한 환경에 맞게 일반화되도록 **프로그래밍적으로** 얻는 것이 좋습니다.  

Gym은 이를 위한 방법을 제공합니다:  
`env.action_space.n`와 `env.observation_space.n`

In [ ]:
state_space =
print("There are ", state_space, " possible states")

action_space =
print("There are ", action_space, " possible actions")

In [ ]:
# Q-테이블을 (상태 공간, 행동 공간) 크기로 생성하고, 각 값을 0으로 초기화해봅시다. np.zeros는 튜플 (a, b)를 필요로 합니다.
def initialize_q_table(state_space, action_space):
  Qtable =
  return Qtable

In [ ]:
Qtable_frozenlake = initialize_q_table(state_space, action_space)

### 해결 방법

In [ ]:
state_space = env.observation_space.n
print("There are ", state_space, " possible states")

action_space = env.action_space.n
print("There are ", action_space, " possible actions")

In [ ]:
# Q-테이블을 (상태 공간, 행동 공간) 크기로 생성하고, 각 값을 0으로 초기화해봅시다. np.zeros는 튜플 (a, b)를 필요로 합니다.
def initialize_q_table(state_space, action_space):
  Qtable = np.zeros((state_space, action_space))
  return Qtable

In [ ]:
Qtable_frozenlake = initialize_q_table(state_space, action_space)

## 탐욕적 정책 정의 🤖

Q-Learning은 **오프-정책** 알고리즘이기 때문에 두 가지 정책을 사용합니다. 이는 **행동을 취할 때와 가치 함수를 업데이트할 때 다른 정책을 사용한다**는 것을 의미합니다.

- **엡실론-탐욕적 정책** (행동 정책)
- **탐욕적 정책** (가치 함수 업데이트 정책)

탐욕적 정책은 Q-Learning 에이전트가 훈련을 완료했을 때 최종적으로 가지게 될 정책이기도 합니다. 탐욕적 정책은 Q-테이블을 사용하여 행동을 선택하는 데 사용됩니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/off-on-4.jpg" alt="Q-Learning" width="100%"/>

In [ ]:
def greedy_policy(Qtable, state):
  # 착취: 가장 높은 상태-행동 값을 가진 행동을 취하기
  action =

  return action

#### 해결 방법

In [ ]:
def greedy_policy(Qtable, state):
  # 착취: 가장 높은 상태-행동 값을 가진 행동을 취하기
  action = np.argmax(Qtable[state][:])

  return action

## 엡실론-탐욕적 정책 정의 🤖

엡실론-탐욕적 정책은 탐색/착취의 균형을 처리하는 훈련 정책입니다.

엡실론-탐욕적 정책의 아이디어는 다음과 같습니다:

- *확률 1 - ɛ* : **착취**를 수행합니다 (즉, 에이전트는 가장 높은 상태-행동 값이 있는 행동을 선택합니다).
  
- *확률 ɛ* : **탐색**을 수행합니다 (무작위 행동을 시도합니다).

훈련이 진행됨에 따라 점차적으로 **엡실론 값을 줄여가며, 탐색은 점점 적게 하고, 착취는 더 많이 하게 됩니다.**

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-learning-4.jpg" alt="Q-Learning" width="100%"/>

In [ ]:
def epsilon_greedy_policy(Qtable, state, epsilon):
  # 0과 1 사이의 무작위 숫자 생성
  random_num =
  # random_num > epsilon이면 --> 착취
  if random_num > epsilon:
    # 현재 상태에서 가장 높은 Q값을 가지는 행동 선택
    # np.argmax가 여기서 유용할 수 있습니다
    action =
  # 그렇지 않으면 --> 탐색
  else:
    action = # 무작위 행동 선택

  return action

#### Solution

In [ ]:
def epsilon_greedy_policy(Qtable, state, epsilon):
  # 0과 1 사이의 무작위 숫자 생성
  random_num = random.uniform(0, 1)
  
  # random_num > epsilon이면 --> 착취
  if random_num > epsilon:
    # 현재 상태에서 가장 높은 Q값을 가지는 행동 선택
    # np.argmax가 여기서 유용할 수 있습니다
    action = greedy_policy(Qtable, state)
  # 그렇지 않으면 --> 탐색
  else:
    # 무작위 행동 선택
    action = env.action_space.sample()

  return action

## 하이퍼파라미터 정의 ⚙️

탐험(exploration)과 관련된 하이퍼파라미터는 가장 중요한 요소 중 하나입니다.

- 에이전트가 **충분히 상태 공간을 탐험**하여 올바른 가치 근사를 학습할 수 있도록 해야 합니다. 이를 위해 epsilon을 점진적으로 감소시키는 방식이 필요합니다.
- epsilon을 너무 빠르게 줄이면 (decay_rate가 너무 크면), **에이전트가 문제를 해결하지 못하고 갇힐 위험이 있습니다**. 이는 상태 공간을 충분히 탐험하지 못해 학습이 불완전해지기 때문입니다.

In [ ]:
# 학습 파라미터
n_training_episodes = 10000  # 전체 학습 에피소드 수
learning_rate = 0.7          # 학습률

# 평가 파라미터
n_eval_episodes = 100        # 전체 평가(테스트) 에피소드 수

# 환경 파라미터
env_id = "FrozenLake-v1"     # 환경 이름
max_steps = 99               # 에피소드당 최대 스텝 수
gamma = 0.95                 # 감가율 (discount factor)
eval_seed = []               # 평가 시 환경의 시드

# 탐험 파라미터
max_epsilon = 1.0             # 초기 탐험 확률
min_epsilon = 0.05            # 최소 탐험 확률
decay_rate = 0.0005           # 탐험 확률의 지수 감쇠율

## 학습 루프 메서드 생성

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-learning-2.jpg" alt="Q-Learning" width="100%"/>

학습 루프는 다음과 같은 흐름으로 진행됩니다:

```
전체 학습 에피소드 수만큼 반복:

  epsilon 감소 (탐험이 점점 덜 필요해짐)
  환경 초기화

    max_steps만큼 반복:
      epsilon-greedy 정책을 사용하여 행동 At 선택
      행동 a를 취하고, 다음 상태 s'와 보상 r 관측
      Bellman 방정식을 사용해 Q값 Q(s,a) 업데이트:
        Q(s,a) ← Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
      종료 조건이면 에피소드 종료
      다음 상태를 현재 상태로 갱신
```

In [ ]:
def train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable):
  for episode in tqdm(range(n_training_episodes)):
    # epsilon 감소 (탐험이 점점 덜 필요해지므로)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    # 환경 초기화
    state, info = env.reset()
    step = 0
    terminated = False
    truncated = False

    # 반복
    for step in range(max_steps):
      # epsilon-greedy 정책을 사용하여 At 행동 선택
      action =

      # At 행동을 취하고 Rt+1과 St+1을 관측
      # 행동 (a)을 취하고 결과 상태(s')와 보상 (r)을 관찰하세요.
      new_state, reward, terminated, truncated, info =

      # Q(s,a) 업데이트: Q(s,a) ← Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
      Qtable[state][action] =

      # 종료 조건이면 에피소드 종료
      if terminated or truncated:
        break

      # 다음 상태를 현재 상태로 갱신
      state = new_state
  return Qtable

#### 해결 방법

In [ ]:
def train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable):
  for episode in tqdm(range(n_training_episodes)):
    # epsilon 감소 (탐험이 점점 덜 필요해지므로)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    # 환경 초기화
    state, info = env.reset()
    step = 0
    terminated = False
    truncated = False

    # 반복
    for step in range(max_steps):
      # epsilon-greedy 정책을 사용하여 At 행동 선택
      action = epsilon_greedy_policy(Qtable, state, epsilon)

      # At 행동을 취하고 Rt+1과 St+1을 관측
      # 행동 (a)을 취하고 결과 상태(s')와 보상 (r)을 관찰하세요.
      new_state, reward, terminated, truncated, info = env.step(action)

      # Q(s,a) 업데이트: Q(s,a) ← Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
      Qtable[state][action] = Qtable[state][action] + learning_rate * (reward + gamma * np.max(Qtable[new_state]) - Qtable[state][action])

      # 종료 조건이면 에피소드 종료
      if terminated or truncated:
        break

      # 다음 상태를 현재 상태로 갱신
      state = new_state
  return Qtable

## Q-Learning 에이전트 학습 🏃

In [ ]:
Qtable_frozenlake = train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable_frozenlake)

## 이제 Q-Learning 테이블이 어떻게 생겼는지 확인해봅시다 👀

In [ ]:
Qtable_frozenlake

## 평가 방법 📝

- Q-Learning 에이전트를 테스트하기 위해 사용할 평가 방법을 정의했습니다.

In [ ]:
def evaluate_agent(env, max_steps, n_eval_episodes, Q, seed):
  """
  Q-Learning 에이전트를 ``n_eval_episodes`` 에피소드 동안 평가하고 평균 보상과 보상의 표준편차를 반환합니다.
  :param env: 평가 환경
  :param max_steps: 에피소드당 최대 스텝 수
  :param n_eval_episodes: 에이전트를 평가할 에피소드 수
  :param Q: Q-테이블
  :param seed: 평가 시 사용할 시드 배열 (taxi-v3의 경우)
  """
  episode_rewards = []
  for episode in tqdm(range(n_eval_episodes)):
    if seed:
      state, info = env.reset(seed=seed[episode])
    else:
      state, info = env.reset()
    step = 0
    truncated = False
    terminated = False
    total_rewards_ep = 0

    for step in range(max_steps):
      # 주어진 상태에서 최대 예상 미래 보상을 가지는 행동 선택
      action = greedy_policy(Q, state)
      new_state, reward, terminated, truncated, info = env.step(action)
      total_rewards_ep += reward

      if terminated or truncated:
        break
      state = new_state
    episode_rewards.append(total_rewards_ep)
  
  mean_reward = np.mean(episode_rewards)
  std_reward = np.std(episode_rewards)

  return mean_reward, std_reward


## Q-Learning 에이전트 평가 📈

- 보통 평균 보상은 1.0이어야 합니다.
- **환경은 상대적으로 쉽습니다**. 상태 공간이 매우 작아서 (16개) 그렇습니다. 환경을 더 복잡하게 만들고 싶다면, [미끄러운 버전](https://gymnasium.farama.org/environments/toy_text/frozen_lake/)으로 바꿔볼 수 있습니다. 이 버전은 확률적 요소를 도입해 환경을 더 복잡하게 만듭니다.

In [ ]:
# 우리 에이전트를 평가하세요.
mean_reward, std_reward = evaluate_agent(env, max_steps, n_eval_episodes, Qtable_frozenlake, eval_seed)
print(f"Mean_reward={mean_reward:.2f} +/- {std_reward:.2f}")

## 학습된 모델을 Hub에 게시하기 🔥

학습 후 좋은 결과를 확인했으므로, **한 줄의 코드로 학습된 모델을 Hub 🤗에 게시할 수 있습니다**.

다음은 모델 카드의 예시입니다:

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/modelcard.png" alt="Model card" width="100%"/>

Hub의 내부에서는 git 기반 저장소를 사용합니다 (git이 무엇인지 모른다고 걱정하지 마세요). 즉, 실험을 진행하고 에이전트를 개선하면서 새로운 버전으로 모델을 업데이트할 수 있다는 의미입니다.

#### 이 코드를 수정하지 마세요

In [ ]:
from huggingface_hub import HfApi, snapshot_download
from huggingface_hub.repocard import metadata_eval_result, metadata_save

from pathlib import Path
import datetime
import json

In [ ]:
def record_video(env, Qtable, out_directory, fps=1):
  """
  에이전트의 재생 영상을 생성합니다.
  :param env: 환경
  :param Qtable: 에이전트의 Q-table
  :param out_directory: 출력 디렉토리
  :param fps: 초당 프레임 수 (taxi-v3와 frozenlake-v1에서는 1을 사용)
  """
  images = []
  terminated = False
  truncated = False
  state, info = env.reset(seed=random.randint(0,500))
  img = env.render()
  images.append(img)
  while not terminated or truncated:
    # 주어진 상태에서 최대 예상 미래 보상을 가지는 행동 선택
    action = np.argmax(Qtable[state][:])
    state, reward, terminated, truncated, info = env.step(action)  # 녹화 로직을 위해 상태는 그대로 둡니다
    img = env.render()
    images.append(img)
  imageio.mimsave(out_directory, [np.array(img) for i, img in enumerate(images)], fps=fps)

In [ ]:
def push_to_hub(
    repo_id, model, env, video_fps=1, local_repo_path="hub"
):
    """
    평가, 비디오 생성 및 허깅 페이스 허브에 모델 업로드.
    이 메서드는 전체 파이프라인을 수행합니다:
    - 모델을 평가합니다.
    - 모델 카드를 생성합니다.
    - 에이전트의 재생 비디오를 생성합니다.
    - 모든 것을 허브에 푸시합니다.

    :param 레포_id: 허깅 페이스 허브의 모델 레포지토리 ID
    :param 환경
    :param 비디오_fps: 비디오 재생을 기록할 초당 프레임 수
    (taxi-v3 및 frozenlake-v1에서는 1을 사용합니다)
    :param 로컬_레포_경로: 로컬 레포지토리가 있는 경로
    """
    _, repo_name = repo_id.split("/")

    eval_env = env
    api = HfApi()

    # Step 1: 레포지토리 생성
    repo_url = api.create_repo(
        repo_id=repo_id,
        exist_ok=True,
    )

    # Step 2: 파일 다운로드
    repo_local_path = Path(snapshot_download(repo_id=repo_id))

    # Step 3: 모델 저장
    if env.spec.kwargs.get("map_name"):
        model["map_name"] = env.spec.kwargs.get("map_name")
        if env.spec.kwargs.get("is_slippery", "") == False:
            model["slippery"] = False

    # 모델 피클링
    with open((repo_local_path) / "q-learning.pkl", "wb") as f:
        pickle.dump(model, f)

    # Step 4: 모델 평가 및 평가 메트릭 포함한 JSON 생성
    mean_reward, std_reward = evaluate_agent(
        eval_env, model["max_steps"], model["n_eval_episodes"], model["qtable"], model["eval_seed"]
    )

    evaluate_data = {
        "env_id": model["env_id"],
        "mean_reward": mean_reward,
        "n_eval_episodes": model["n_eval_episodes"],
        "eval_datetime": datetime.datetime.now().isoformat()
    }

    # 평가 결과를 포함한 "results.json" 파일 생성
    with open(repo_local_path / "results.json", "w") as outfile:
        json.dump(evaluate_data, outfile)

    # Step 5: 모델 카드 생성
    env_name = model["env_id"]
    if env.spec.kwargs.get("map_name"):
        env_name += "-" + env.spec.kwargs.get("map_name")

    if env.spec.kwargs.get("is_slippery", "") == False:
        env_name += "-" + "no_slippery"

    metadata = {}
    metadata["tags"] = [env_name, "q-learning", "reinforcement-learning", "custom-implementation"]

    # 메트릭 추가
    eval = metadata_eval_result(
        model_pretty_name=repo_name,
        task_pretty_name="reinforcement-learning",
        task_id="reinforcement-learning",
        metrics_pretty_name="mean_reward",
        metrics_id="mean_reward",
        metrics_value=f"{mean_reward:.2f} +/- {std_reward:.2f}",
        dataset_pretty_name=env_name,
        dataset_id=env_name,
    )

    # 두 딕셔너리 병합
    metadata = {**metadata, **eval}

    model_card = f"""
  # **Q-Learning** Agent playing1 **{env_id}**
  This is a trained model of a **Q-Learning** agent playing **{env_id}** .

  ## Usage

  ```python

  model = load_from_hub(repo_id="{repo_id}", filename="q-learning.pkl")

  # Don't forget to check if you need to add additional attributes (is_slippery=False etc)
  env = gym.make(model["env_id"])
  ```
  """

    evaluate_agent(env, model["max_steps"], model["n_eval_episodes"], model["qtable"], model["eval_seed"])

    readme_path = repo_local_path / "README.md"
    readme = ""
    print(readme_path.exists())
    if readme_path.exists():
        with readme_path.open("r", encoding="utf8") as f:
            readme = f.read()
    else:
        readme = model_card

    with readme_path.open("w", encoding="utf-8") as f:
        f.write(readme)

    # Readme 메타데이터에 메트릭 저장
    metadata_save(readme_path, metadata)

    # Step 6: 비디오 녹화
    video_path = repo_local_path / "replay.mp4"
    record_video(env, model["qtable"], video_path, video_fps)

    # Step 7. 모든 것을 Hub에 푸시
    api.upload_folder(
        repo_id=repo_id,
        folder_path=repo_local_path,
        path_in_repo=".",
    )

    print("모델이 Hub에 업로드되었습니다. 모델을 여기서 확인할 수 있습니다: ", repo_url)

### .

`push_to_hub`를 사용하면 **에이전트를 평가하고, 재생 영상을 기록하고, 모델 카드를 생성하여 Hub에 푸시할 수 있습니다**.

이 방식으로:
- **우리의 작업을 보여줄 수 있습니다** 🔥
- **에이전트가 플레이하는 모습을 시각화할 수 있습니다** 👀
- **다른 사람들이 사용할 수 있는 에이전트를 커뮤니티와 공유할 수 있습니다** 💾
- **리더보드를 통해 에이전트의 성능을 확인할 수 있습니다 🏆** 👉 [Deep Reinforcement Learning Leaderboard](https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard)

모델을 커뮤니티와 공유하려면 세 가지 단계를 더 따라야 합니다:

1️⃣ (아직 하지 않았다면) Hugging Face에 계정을 생성하세요 ➡ [https://huggingface.co/join](https://huggingface.co/join)

2️⃣ 로그인 후, Hugging Face 웹사이트에서 인증 토큰을 저장해야 합니다.
- 새로운 토큰을 생성하려면 [여기](https://huggingface.co/settings/tokens)에서 **쓰기 역할**로 생성하세요.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/create-token.jpg" alt="Create HF Token">

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

Google Colab이나 Jupyter Notebook을 사용하지 않는 경우, 아래 명령어를 대신 사용해야 합니다: `huggingface-cli login`

3️⃣ 이제 `push_to_hub()` 함수를 사용하여 훈련된 에이전트를 🤗 Hub에 푸시할 준비가 되었습니다 🔥

- **모델 딕셔너리**를 생성하여 하이퍼파라미터와 Q_table을 포함시켜야 합니다.

In [ ]:
model = {
    "env_id": env_id,
    "max_steps": max_steps,
    "n_training_episodes": n_training_episodes,
    "n_eval_episodes": n_eval_episodes,
    "eval_seed": eval_seed,

    "learning_rate": learning_rate,
    "gamma": gamma,

    "max_epsilon": max_epsilon,
    "min_epsilon": min_epsilon,
    "decay_rate": decay_rate,

    "qtable": Qtable_frozenlake
}

`push_to_hub` 함수를 다음과 같이 채워봅시다:

- `repo_id`: 생성되거나 업데이트될 Hugging Face Hub 저장소의 이름  
(`repo_id = {username}/{repo_name}`)  
💡 좋은 `repo_id` 예시: `{username}/q-{env_id}`
- `model`: 하이퍼파라미터와 Qtable을 포함한 모델 딕셔너리
- `env`: 환경
- `commit_message`: 커밋 메시지

In [ ]:
model

In [ ]:
username = "" # 이것을 채우세요
repo_name = "q-FrozenLake-v1-4x4-noSlippery"
push_to_hub(
    repo_id=f"{username}/{repo_name}",
    model=model,
    env=env)

축하합니다 🥳 처음부터 직접 구현하고, 학습시키고, 첫 번째 강화학습 에이전트를 업로드했습니다.  
`FrozenLake-v1 no_slippery`는 매우 간단한 환경이었으니, 이제 더 어려운 환경에 도전해봅시다 🔥.

# Part 2: Taxi-v3 🚖

## `Taxi-v3 🚕` 만들고 이해하기  
---

💡 환경을 처음 사용할 때는 문서를 확인하는 습관을 들이세요

👉 https://gymnasium.farama.org/environments/toy_text/taxi/

---

`Taxi-v3` 🚕에서는 격자 세계(grid world)에 R(빨강), G(초록), Y(노랑), B(파랑) 네 개의 지정된 위치가 있습니다.

에피소드가 시작되면 **택시는 무작위 칸에서 시작**하고, 승객도 무작위 위치에 있습니다.  
택시는 승객 위치로 이동하여 **승객을 태운 뒤**, 승객의 목적지(지정된 네 위치 중 하나)로 이동하고 **승객을 하차**시킵니다.  
승객이 하차되면 에피소드가 종료됩니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/taxi.png" alt="Taxi">

In [25]:
env = gym.make("Taxi-v3", render_mode="rgb_array")

**500개의 이산 상태**가 있습니다. 이는 **택시 위치 25가지, 승객의 가능한 위치 5가지** (승객이 택시 안에 있는 경우 포함), 그리고 **목적지 위치 4가지**가 있기 때문입니다.

In [26]:
state_space = env.observation_space.n
print("There are ", state_space, " possible states")

There are  500  possible states


In [27]:
action_space = env.action_space.n
print("There are ", action_space, " possible actions")

There are  6  possible actions


행동 공간 (에이전트가 취할 수 있는 가능한 행동들의 집합)은 **6개의 이용 가능한 행동 🎮**으로 이루어진 이산적 공간입니다:

- 0: 남쪽으로 이동
- 1: 북쪽으로 이동
- 2: 동쪽으로 이동
- 3: 서쪽으로 이동
- 4: 승객 태우기
- 5: 승객 내려주기

보상 함수 💰:

- 다른 보상이 트리거되지 않는 한, 단계당 -1.
- 승객 전달 시 +20.
- “승객 태우기” 및 “승객 내려주기” 행동을 불법적으로 실행 시 -10.

In [28]:
# state_size 행과 action_size 열(500x6)을 갖는 Q 테이블을 생성합니다.
Qtable_taxi = initialize_q_table(state_space, action_space)
print(Qtable_taxi)
print("Q-table shape: ", Qtable_taxi .shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Q-table shape:  (500, 6)


## 하이퍼파라미터 정의 ⚙️

⚠ EVAL_SEED를 수정하지 마세요: eval_seed 배열은 **모든 학우에게 동일한 택시 시작 위치로 에이전트를 평가할 수 있도록 합니다**

In [30]:
# 훈련 파라미터
n_training_episodes = 25000   # 총 훈련 에피소드 수
learning_rate = 0.7           # 학습률

# 평가 파라미터
n_eval_episodes = 100         # 총 테스트 에피소드 수

# EVAL_SEED 수정 금지
eval_seed = [16,54,165,177,191,191,120,80,149,178,48,38,6,125,174,73,50,172,100,148,146,6,25,40,68,148,49,167,9,97,164,176,61,7,54,55,
  161,131,184,51,170,12,120,113,95,126,51,98,36,135,54,82,45,95,89,59,95,124,9,113,58,85,51,134,121,169,105,21,30,11,50,65,12,43,82,145,152,97,106,55,31,85,38,
  112,102,168,123,97,21,83,158,26,80,63,5,81,32,11,28,148] # 평가 시드, 이는 모든 학우의 에이전트가 동일한 택시 시작 위치에서 훈련되도록 보장합니다
                                                         # 각 시드는 특정 시작 상태를 가집니다

# 환경 파라미터
env_id = "Taxi-v3"            # 환경 이름
max_steps = 99                # 에피소드당 최대 스텝 수
gamma = 0.95                  # 감가율 (할인율)

# 탐험 파라미터
max_epsilon = 1.0             # 시작 시 탐험 확률
min_epsilon = 0.05            # 최소 탐험 확률
decay_rate = 0.005            # 탐험 확률의 지수 감소율

## Q-Learning 에이전트 훈련시키기 🏃

In [31]:
Qtable_taxi = train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable_taxi)
Qtable_taxi

  0%|          | 0/25000 [00:00<?, ?it/s]

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  2.75200369,   3.94947757,   2.75200369,   3.94947757,
          5.20997639,  -5.05052243],
       [  7.93349184,   9.40344144,   7.93349184,   9.40367562,
         10.9512375 ,   0.40367548],
       ...,
       [ -3.09408412,  12.58025   ,  -2.9070066 ,  -3.8221694 ,
         -2.2027986 , -10.62089056],
       [ -3.88608682,   6.53681724,  -3.95785867,  -4.13398518,
        -12.16948305,  -5.57355163],
       [ -1.3755    ,  -1.3755    ,  15.44934586,  18.        ,
          5.59967048,   6.93507486]])

## 모델 딕셔너리 생성 💾 및 훈련된 모델 허브에 게시 🔥

- 재현성을 위한 모든 훈련 하이퍼파라미터와 Q-테이블을 포함할 모델 딕셔너리를 생성합니다.

In [32]:
model = {
    "env_id": env_id,
    "max_steps": max_steps,
    "n_training_episodes": n_training_episodes,
    "n_eval_episodes": n_eval_episodes,
    "eval_seed": eval_seed,

    "learning_rate": learning_rate,
    "gamma": gamma,

    "max_epsilon": max_epsilon,
    "min_epsilon": min_epsilon,
    "decay_rate": decay_rate,

    "qtable": Qtable_taxi
}

In [ ]:
username = "" # 이것을 채우세요
repo_name = "" # 이것을 채우세요
push_to_hub(
    repo_id=f"{username}/{repo_name}",
    model=model,
    env=env)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

.gitattributes:   0%|          | 0.00/1.52k [00:00<?, ?B/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (550, 350) to (560, 352) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


False


replay.mp4:   0%|          | 0.00/117k [00:00<?, ?B/s]

q-learning.pkl:   0%|          | 0.00/24.6k [00:00<?, ?B/s]

Upload 2 LFS files:   0%|          | 0/2 [00:00<?, ?it/s]

모델이 Hub에 업로드되었습니다. 모델을 여기서 확인할 수 있습니다:  https://huggingface.co/Yeongi/q-Taxi-v3


이제 모델이 Hugging Face Hub에 업로드되었으니, 리더보드를 통해 여러분의 `Taxi-v3` 결과를 다른 학습자들과 비교해볼 수 있습니다 🏆 👉 https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/taxi-leaderboard.png" alt="Taxi Leaderboard">

# Part 3: 허브에서 불러오기 🔽

Hugging Face Hub 🤗의 멋진 점은 커뮤니티에서 공유한 강력한 모델들을 아주 쉽게 불러올 수 있다는 것입니다.

Hub에서 저장된 모델을 불러오는 방법은 매우 간단합니다:

1. https://huggingface.co/models?other=q-learning 에 접속해 q-learning으로 저장된 모든 모델 리스트를 확인합니다.  
2. 원하는 모델을 선택하고 `repo_id`를 복사합니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/notebooks/unit2/copy-id.png" alt="Copy id">

3. 그런 다음 `load_from_hub` 함수를 사용할 때는 다음 두 가지를 지정해주면 됩니다:
- `repo_id`: 복사한 저장소 ID  
- `filename`: 해당 저장소 안에 저장된 모델 파일 이름

#### 이 코드를 수정하지 마세요

In [34]:
from urllib.error import HTTPError
from huggingface_hub import hf_hub_download


def load_from_hub(repo_id: str, filename: str) -> str:
    """
    Hugging Face Hub에서 모델을 다운로드합니다.
    :param repo_id: Hugging Face Hub에서 모델 저장소의 ID
    :param filename: 저장소에서 모델 zip 파일 이름
    """
    # Hub에서 모델을 가져오고, 로컬 디스크에 다운로드 및 캐시합니다
    pickle_model = hf_hub_download(
        repo_id=repo_id,
        filename=filename
    )

    with open(pickle_model, 'rb') as f:
        downloaded_model_file = pickle.load(f)

    return downloaded_model_file

### .

In [35]:
model = load_from_hub(repo_id="ThomasSimonini/q-Taxi-v3", filename="q-learning.pkl") # 다른 모델을 사용해 보세요

print(model)
env = gym.make(model["env_id"])

evaluate_agent(env, model["max_steps"], model["n_eval_episodes"], model["qtable"], model["eval_seed"])

q-learning.pkl:   0%|          | 0.00/24.6k [00:00<?, ?B/s]

{'env_id': 'Taxi-v3', 'max_steps': 99, 'n_training_episodes': 25000, 'n_eval_episodes': 100, 'eval_seed': [16, 54, 165, 177, 191, 191, 120, 80, 149, 178, 48, 38, 6, 125, 174, 73, 50, 172, 100, 148, 146, 6, 25, 40, 68, 148, 49, 167, 9, 97, 164, 176, 61, 7, 54, 55, 161, 131, 184, 51, 170, 12, 120, 113, 95, 126, 51, 98, 36, 135, 54, 82, 45, 95, 89, 59, 95, 124, 9, 113, 58, 85, 51, 134, 121, 169, 105, 21, 30, 11, 50, 65, 12, 43, 82, 145, 152, 97, 106, 55, 31, 85, 38, 112, 102, 168, 123, 97, 21, 83, 158, 26, 80, 63, 5, 81, 32, 11, 28, 148], 'learning_rate': 0.7, 'gamma': 0.95, 'epsilon': 1.0, 'max_epsilon': 1.0, 'min_epsilon': 0.05, 'decay_rate': 0.005, 'qtable': array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 2.75200369,  3.94947757,  2.75200369,  3.94947757,  5.20997639,
        -5.05052243],
       [ 7.93349184,  9.40367562,  7.93349184,  9.40367562, 10.9512375 ,
         0.40367562],
       ...,
       [10.9512375 , 12.58025   , 10

  0%|          | 0/100 [00:00<?, ?it/s]

(7.56, 2.706732347314747)

In [36]:
model = load_from_hub(repo_id="ThomasSimonini/q-FrozenLake-v1-no-slippery", filename="q-learning.pkl") # 다른 모델을 사용해 보세요

env = gym.make(model["env_id"], is_slippery=False)

evaluate_agent(env, model["max_steps"], model["n_eval_episodes"], model["qtable"], model["eval_seed"])

q-learning.pkl:   0%|          | 0.00/933 [00:00<?, ?B/s]

  0%|          | 0/100 [00:00<?, ?it/s]

(1.0, 0.0)

## 추가 도전 과제들 🏆

**가장 좋은 학습 방법은 직접 해보는 것!**  
지금까지 본 것처럼, 현재의 에이전트는 아주 뛰어난 성능을 보이지는 않아요.  
첫 번째 제안은 **학습 횟수를 늘리는 것**입니다. 예를 들어 1,000,000 스텝으로 학습한 결과는 꽤 괜찮았습니다!

[리더보드](https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard)에서 당신의 에이전트를 확인해보세요.  
**정상에 오를 수 있을까요?**

리더보드 순위를 올리기 위한 몇 가지 아이디어:

- 더 많은 스텝으로 학습하기  
- 클래스메이트들이 사용한 **하이퍼파라미터**를 참고해 다른 설정 시도해보기  
- **새롭게 학습한 모델을 Hub에 업로드**하기 🔥  

빙판 위를 걷거나 택시 운전이 너무 지루하다면?  
**환경을 바꿔보세요!**  
예를 들어 `FrozenLake-v1`의 미끄러운(slippery) 버전은 어떤가요?  
[Gymnasium 문서](https://gymnasium.farama.org/)를 참고해서 작동 방식도 확인하고, 재미있게 실험해보세요 🎉

_____________________________________________________________________

축하합니다 🥳 처음으로 강화학습 에이전트를 직접 구현하고, 학습시키고, 업로드까지 완료했습니다!

Q-Learning을 이해하는 것은 **가치 기반(value-based) 방법론을 이해하는 데 있어 매우 중요한 단계**입니다.

다음 유닛에서는 Deep Q-Learning을 다루게 됩니다.  
Q-테이블을 만들고 업데이트하는 방식은 좋은 전략이지만 — **확장성이 떨어진다는 단점이 있습니다.**

예를 들어, Doom 게임을 학습하는 에이전트를 만든다고 상상해보세요.

<img src="https://vizdoom.cs.put.edu.pl/user/pages/01.tutorial/basic.png" alt="Doom"/>

Doom 같은 환경은 상태 공간이 매우 크고, 수백만 개의 상태가 존재합니다.  
이런 환경에서는 Q-테이블을 생성하고 유지하는 것이 비효율적입니다.

그래서 다음 유닛에서는 Deep Q-Learning을 배웁니다.  
Deep Q-Learning은 **신경망을 사용하여, 주어진 상태에서 가능한 행동들 각각의 Q값을 근사**하는 알고리즘입니다.

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit4/atari-envs.gif" alt="Environments"/>

Unit 3에서 만나요! 🔥  

## 계속 배우고, 멋지게 나아가요 🤗